image: maven:3.9.6-amazoncorretto-17

definitions:
  steps:
    - step: &build
        name: Build the application
        caches:
          - maven
        script:
          - mvn -B clean package -DskipTests --file pom.xml
        artifacts:
          - target/*.jar

    - step: &test
        name: Run Tests and Generate Coverage Report
        caches:
          - maven
        script:
          - mvn -B clean verify --file pom.xml
        artifacts:
          - target/site/jacoco/*

pipelines:
  default:
    - step: *build
    - step: *test
