image: maven:3.6.3

definitions:
  steps:
    - step: &build
        name: Build the application
        caches:
          - maven
        script:
          - mvn -B clean package --file pom.xml
        artifacts:
          - target/*.jar

pipelines:
  default:
      - step: *build

